export const CourseStates = {
    COURSES_REQUEST: 'COURSES_REQUEST',
    GET_ALL_COURSES_SUCCESS: 'GET_ALL_COURSES_SUCCESS',
    GET_ALL_COURSES_FAILURE: 'GET_ALL_COURSES_FAILURE',
    Create_NEW_COURSE_SUCCESS: 'Create_NEW_COURSE_SUCCESS',
    Create_NEW_COURSE_FAILURE: 'Create_NEW_COURSE_FAILURE',
    UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
    UPDATE_COURSE_FAILURE: 'UPDATE_COURSE_FAILURE',
    DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
    DELETE_COURSE_FAILURE: 'DELETE_COURSE_FAILURE',
};